version: 2.1

executors:
  container-runner:
    docker:
      - image: cimg/go:1.26
    resource_class: logan/small

parameters:
  server-id:
    default: ""
    type: string

jobs:
  update-server:
    executor: container-runner
    environment:
      SERVER_ID: << pipeline.parameters.server-id >>
    steps:
      - checkout
      - run:
          name: Update Discord and Reinstall Server
          command: |
            if [ -z "$SERVER_ID" ]; then
              echo "Error: SERVER_ID is not set or empty."
              circleci step halt
            else
              go run ./cmd/main.go
            fi
            
workflows:
  update-server:
    jobs:
      - update-server:
          context: [ SERVER_UPDATER ]
